---
# tasks file for ec2-facts
- name: Fetch Instance Info
  ec2_instance_facts:
    region: us-east-1
    filters:
      "tag:instance_filter": "three-tier-app-pipatel*"
  register: ec2_instance_facts

- name: Add host
  add_host:
    name: "{{ item.public_ip_address }}"
    groups:
      - "{{ item.tags.Name }}"
      - "{{ item.tags.AnsibleGroup }}"
    ansible_ssh_private_key_file: "/tmp/projkey.pem"
  with_items: "{{ ec2_instance_facts.instances }}"
