---
# tasks file for roles/win_ad_user

- name: create windows domain groups
  win_domain_group:
    name: "{{ item.group_name }}"
    scope: "{{ item.group_scope }}"
    state: present
  with_items: "{{ user_info }}"

- name: create AD user
  win_domain_user:
    name: "{{ item.name }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    groups: "{{ item.group_name }}"
    state: present
    email: "{{ item.name }}@ad1.f9d5.example.opentlc.com"
    update_password: on_create
  with_items: "{{ user_info }}"
