---
# tasks file for osp-facts
   - name: Fetch Instance Info
     os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      groups:
        - "{{ item.metadata.group }}"
        - "{{ item.metadata.deployment_name }}"
      ansible_ssh_private_key_file: /root/.ssh/openstack.pem
      ansible_user: cloud-user
     with_items: "{{ openstack_servers }}"
