---
- name: Cleanup OSP environment
  hosts: jumpbox
  tasks:
    - name: Gather instance information
      os_server_facts:
        cloud: ospcloud
    - block:
      - name: Purge floating IP from instance
        os_floating_ip:
          cloud: ospcloud
          state: absent
          reuse: yes
          server: "{{ instance_name }}"
          network: ext_network
          wait: true
          timeout: 180
          purge: true
        vars:
          instance_name: "{{ item.name }}"
        with_items: openstack_servers

      - name: Remove instances
        os_server:
          cloud: ospcloud
          name: "{{ instance_name }}"
          state: absent
        vars:
          instance_name: "{{ item.name }}"
        with_items: openstack_servers
      when: openstack_servers | length > 0

    - name: Remove m2.small flavor
      os_nova_flavor:
       cloud: ospcloud
       state: absent
       name: m2.small

    - name: Remove all security groups
      os_security_group:
        cloud: ospcloud
        name: "{{ security_group_name }}"
        state: absent
      vars:
        security_group_name: "{{ item_servers }}"
      with_items:
        - frontend
        - db
        - app
