---
- name: Cleanup OSP environment
  hosts: jumpbox
  tasks:
    - name: Gather instance information
      os_server_facts:
        cloud: ospcloud
    - block:
      - name: Purge floating IP from instance
        os_floating_ip:
          cloud: ospcloud
          state: absent
          reuse: yes
          server: "{{ instance_name }}"
          network: ext_network
          wait: true
          timeout: 180
          purge: true
        vars:
          instance_name: "{{ item.name }}"
        with_items: openstack_servers

      - name: Remove instances
        os_server:
          cloud: ospcloud
          name: "{{ instance_name }}"
          state: absent
        vars:
          instance_name: "{{ item.name }}"
        with_items: openstack_servers
      when: openstack_servers | length > 0

    - name: Remove m2.small flavor
      os_nova_flavor:
       cloud: ospcloud
       state: absent
       name: m2.small

    - name: Remove all security groups
      os_security_group:
        cloud: ospcloud
        name: "{{ security_group_name }}"
        state: absent
      vars:
        security_group_name: "{{ item }}_servers"
      with_items:
        - frontend
        - db
        - app

    - name: Remove keypair
      os_keypair:
        cloud: ospcloud
        state: absent
        name: ansible_ssh

    - name: Remove router
      os_router:
        name: router1
        state: absent

    - name: Remove internal subnet
      os_subnet:
        cloud: ospcloud
        state: absent
        network_name: int_network
        name: int_subnet

    - name: Remove external subnet
      os_subnet:
        cloud: ospcloud
        state: absent
        network_name: ext_network
        name: external_subnet

    - name: Remove networks
      os_network:
        cloud: ospcloud
        state: absent
        name: "{{ network_name }}"
      vars:
        network_name: "{{ item }}"
      with_items:
        - ext_network
        - int_network
