---
- name: Provision Production environment for 3-Tier application
  gather_facts: false
  hosts: localhost
  tasks:
    - name: create bin directory
      file:
        path: ~/bin
        state: directory
        mode: 0755

    - name: download common.sh
      get_url:
        url: http://www.opentlc.com/download/ansible_bootcamp/scripts/common.sh
        dest: ~/bin/common.sh
        mode: 0755

    - name: download jq
      get_url:
        url: http://www.opentlc.com/download/ansible_bootcamp/scripts/jq-linux64
        dest: ~/bin/jq
        mode: 0755

    - name: download order_svc.sh
      get_url:
        url: http://www.opentlc.com/download/ansible_bootcamp/scripts/order_svc.sh
        dest: ~/bin/order_svc.sh
        mode: 0755

    - name: order prod env from AWS
      script: order_prod_env.sh

    - name: wait for order to be fulfilled
      wait_for:
        timeout: 1200
