---
- name: test web page
  hosts: localhost
  gather_facts: false
  roles:
    - ec2-facts
  tasks:
    - name: access local webpage 1st time
      uri:
        url="http://{{ frontend_ip }}"
      register: webpage
      vars:
        frontend_ip: "{{ groups['frontends'][0] }}"
    - fail:
        msg: "Failed"
      when: webpage.status != 200

    - name: access local webpage 2nd time
      uri:
        url="http://{{ frontend_ip }}"
      register: webpage
      vars:
        frontend_ip: "{{ groups['frontends'][0] }}"
      when: webpage.status != 200
