---
# tasks file for roles/win_service_config
- name: install package
  win_chocolatey:
    name: "{{ package_name }}"
    params: "{{ parameters }}"
    state: present
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: enable service
  win_service:
    name: "{{ service_name }}"
    state: started
    start_mode: auto
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: add win firewall rule
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
